from locust import HttpUser, task
import random

srvc = ["Auth","User","Profile","Billing","Payments","Orders","Inventory","Shipping","Tracking","Cart","Checkout","Catalog","Products","Reviews","Analytics","Reports","Notifications","Email",
"SMS","Search","Recommender","Session","Gateway",
"API", "Identity","OAuth","Logs","Events","Metrics","Cache","Storage","File","Media","Stream","Chat","Messaging","Payments","Fraud","Subscriptions","Webhooks","Tasks","Workflow","Sync","Admin","Gateway","Dispatcher","Scheduler","Processor","Worker","Backup"]

msg = ["[INFO] User 'hassan' successfully logged in.", "[INFO] Order #12345 created for user ID 789.", "[INFO] Payment processed: $99.99 for Order #98765.", "[INFO] Email sent to user@example.com.", "[INFO] Product catalog synced with external API.", "[INFO] Cache refreshed for product ID 456.", "[INFO] Webhook received from Stripe.", "[INFO] File uploaded: invoice_123.pdf.", "[INFO] New subscription created for user 56789.", "[INFO] Background job ‘report_generator’ started.", "[WARNING] API rate limit exceeded for IP 192.168.1.10.", "[WARNING] Payment gateway response delayed (5s).", "[WARNING] Failed login attempt for user 'admin'.", "[WARNING] Missing expected field 'email' in request payload.", "[WARNING] High memory usage detected (85%).", "[WARNING] Fallback to default currency (USD) due to missing exchange rates.", "[WARNING] Slow query detected: SELECT * FROM users took 10s.", "[WARNING] SMS delivery failed, retrying...", "[WARNING] Temporary cache miss for product 98765.", "[WARNING] Unusual spike in failed transactions detected.", "[ERROR] Database connection failed: timeout after 30s.", "[ERROR] Payment failed: Insufficient funds.", "[ERROR] User registration failed: Duplicate email found.", "[ERROR] File upload error: Disk quota exceeded.", "[ERROR] Unauthorized access attempt to /admin.", "[ERROR] Redis cache unavailable, falling back to database.", "[ERROR] API request to external service failed: 500 Internal Server Error.", "[ERROR] Order processing failed: No stock available.", "[ERROR] Transaction rollback due to validation error.", "[ERROR] JWT token expired for user ID 56789.", "[CRITICAL] System memory usage exceeded 95%, triggering emergency shutdown.", "[CRITICAL] Data corruption detected in order database!", "[CRITICAL] Security breach detected: Unauthorized API key usage.", "[CRITICAL] Web server crashed: Too many open connections.", "[CRITICAL] Payment service unreachable, all transactions failing.", "[CRITICAL] Master database node down, failing over to replica.", "[CRITICAL] Disk full: No space left on device.", "[CRITICAL] Unexpected kernel panic detected! Restarting service...", "[CRITICAL] Distributed system split-brain detected in cluster.", "[CRITICAL] Message queue backlog exceeded critical threshold.", "[DEBUG] Fetching user profile for ID 12345.", "[DEBUG] API response time: 120ms for endpoint /products.", "[DEBUG] Retrying failed request to external service (attempt 3).", "[DEBUG] Generated JWT token for session ID abc123.", "[DEBUG] Querying database for active orders...", "[DEBUG] Load balancer assigned request to server node-02.", "[DEBUG] Parsing JSON payload: { \"user_id\": 98765 }", "[DEBUG] Session expired for user ID 65432.", "[DEBUG] Message published to Kafka topic 'orders' with key 12345.", "[DEBUG] New deployment detected: Version 2.1.0."]


class WebsiteUser(HttpUser):
    @task
    def load_test(self):
        self.client.post("/", headers={
            "kv-service": random.choice(srvc),
        }, data=random.choice(msg))
